### ISSUE TITLE
v1.2 doesn't work.

### ISSUE THREAD

**Issue by GuruGitHubTheG** [BarRaider/streamdeck-foldereditor#8]
It just displays "Enter the Column to put the back folder on [0--1]:" and when you type anything besides 0 (i.e. 1), it just says the number is too high. Same for the Row selector. I am using the already compiled version.

**Comment by Mikrz** [comment]
This is probably the same issue I experienced, and fixed, in #7. It's due to the model number being changed, probably some internal hardware revision. If you know how to compile from source, the feature branch on my fork seems to be fully functional if your model number matches mine (20GAA9902).

Maybe @BarRaider has a moment to merge my PR so this issue can be fixed for more people to use this great little tool. :)

**Comment by evilryan** [comment]
Same issue:

```
PS C:\etc\Stream Deck> .\folder_editor.exe
Stream Deck 'Folder-Back' Editor v1.2 by BarRaider
View my other projects on: https://BarRaider.github.io
DISCLAIMER: This may damage your profiles! Use with caution and under your own risk
To make sure I stress this enough - this usually works but you MAY loose the profile - make a backup by EXPORTING the profile before running this app...
[1] Default Profile
[2] Default Stream Deck
[3] Volume Controller XL (Auto)
[4] WinToolsXL
Enter the number of the profile to edit: 2
GENERAL ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at streamdeck_foldereditor.ProfilesExplorer.FindProfileFolderActions(ProfileInfo profileInfo) in E:\Projects\GitHub\streamdeck-foldereditor\streamdeck-foldereditor\ProfilesExplorer.cs:line 69
   at streamdeck_foldereditor.Program.GetFolderLocationToEdit(ProfileInfo profileInfo) in E:\Projects\GitHub\streamdeck-foldereditor\streamdeck-foldereditor\Program.cs:line 69
   at streamdeck_foldereditor.Program.Main(String[] args) in E:\Projects\GitHub\streamdeck-foldereditor\streamdeck-foldereditor\Program.cs:line 20

*** For help go to https://BarRaider.github.io ***
PS C:\etc\StreamDeck>
```

**Comment by BarRaider** [comment]
The profile schema was changed in Stream Deck v6. Currently this program will not work.
Some parts of the new schema are unclear, will need to see if it's worth investing in this

**Comment by evilryan** [comment]
> The profile schema was changed in Stream Deck v6. Currently this program will not work. Some parts of the new schema are unclear, will need to see if it's worth investing in this

Seems like such a trivial thing for Elgato/Corsair to implement it in the core application. Since it doesn't affect the functionality of the device, I understand the situation as it is.

Thanks for the reply!

**Comment by Mikrz** [comment]
I personally had a look into the new format, and there's some weird hashing of profile and folder names/ids going on, but it's otherwise quite a logical format still, so it is just a matter of rewriting the app to handle the new format. Unfortunately that isn't a quick task, but I might look into it myself at some point when I have time.

**Comment by BarRaider** [comment]
> I personally had a look into the new format, and there's some weird hashing of profile and folder names/ids going on, but it's otherwise quite a logical format still

Well, if you are able to come up with the hash function, do let us know. Otherwise, it's not a trivial task.

**Comment by schwarzie2478** [comment]
I played around with the profiles today and I was able to manipulate the json succesfully manually.
Not sure what the hash is all about in the discussion above.

I just copied the block from [0,0]  and I did use the same actionid guid. 

So for if you really want it you can do it yourself. 
I'll take a look at the code if I can make an update.

**Comment by Mikrz** [comment]
> I just copied the block from [0,0]  and I did use the same actionid guid. 

The hashes are how the folders and parents/children are related. Without knowing that, it makes it difficult to automate adjustments without it being trial and error. The utility doesn't know what the appearance of the folders is, so it can't easily determine what is what for folder manipulation.

**Comment by Mibix** [comment]
So this no longer works?

**Comment by somedaygone** [comment]
If this is known not to work, a prominent comment in the README would be nice. Thank you for everything you do for the Stream Deck community!

**Comment by BarRaider** [comment]
Sorry for the delay. Changes in the Elgato profile structure required a major overahaul to the code.
Should now work in latest v2.0 release
